"""Added desc column

Revision ID: 4e5da30cedf6
Revises: f4aa97f102
Create Date: 2012-04-04 14:29:45.532712

"""

# revision identifiers, used by Alembic.
revision = '4e5da30cedf6'
down_revision = 'f4aa97f102'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pastes', sa.Column('desc', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pastes', 'desc')
    ### end Alembic commands ###
